name: raspi-gpio-snap
base: core18
version: '0.1'
summary: raspi-gpio utility, for use on Ubuntu Core
description: |
  Simple raspi-gpio utility, from https://github.com/RPi-Distro/raspi-gpio 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict
architectures:
  - build-on: [amd64]
    run-on: [armhf, arm64]


parts:
  bin-part:
    plugin: dump
    source: bin/

apps:
  raspi-gpio:
    command: raspi-gpio-armhf
    plugs: [ gpio-memory-control ]
